### ISSUE TITLE
Cannot force record an event

### ISSUE THREAD

**Issue by premnirmal** [Indicative/Indicative-Android#2]
It would be nice if the api provided a method that allows the dev to force record an event

**Comment by cfei18** [comment]
Thanks Prem, we'll take a look shortly.

**Comment by jackie-benowitz** [comment]
Hey Prem -- Just pushed an updated version that provides a static method so you can sync all events in the cache.  Please let me know if you have any questions!  Thanks for all your feedback on the Client, it's very useful!

**Comment by premnirmal** [comment]
no problem, thanks for addressing this!
