### ISSUE TITLE
Add to maven central

### ISSUE THREAD

**Issue by premnirmal** [Indicative/Indicative-Android#3]
Can you add Indicative-Android to maven central? I only see Indicative-Java there

**Comment by bealeindicative** [comment]
Hey Prem,

The Android client is up on Maven Central now: http://search.maven.org/#artifactdetails%7Ccom.indicative.client.android%7CIndicative-Android%7C1.0.1%7Caar

Thanks for this -- it was a great suggestion.  Let us know if there are any other helpful changes we can make!

**Comment by premnirmal** [comment]
thanks @bealeindicative . this way we can update the version in our build.gradle whenever there's a new version

**Comment by sriramkraman** [comment]
:+1:
